### ISSUE TITLE
Error: Type 'uint8_t' could not be resolved

### ISSUE THREAD

**Issue by agustinlk** [sisoputnfrba/osada-utils#2]
Buenas tardes!
Este error me da de arranque, solo cuando agrego a mi proyecto el osada.h. Busqué por todos lados de por qué no reconoce el tipo y no encontré nada. En un foro decían que este tipo de datos está definido en la librería <cstdint>; la incluí,  pero nada. Yo ya había creado la estructura pero usando int, por eso no tenía problema. Alguna idea? Gracias!

Agustìn

**Comment by agustinlk** [comment]
Me importé al proyecto el osada.h otra vez, le hice el include de <stdint.h> y ahora si me los reconoce. No se que habría pasado. Cierro el issue.

**Comment by mgarciaisaia** [comment]
Efectivamente, era un bug - lo corregimos con 718f25c402e7702d1bf275f748188887edcf531e.

¡Gracias por el aviso!
