### ISSUE TITLE
Error al generar filesystem de 2G

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/osada-utils#3]
Buenas noches a todos,

Estoy intentando generar un filesystem de 2GB (el máximo puede ser de 4GB) y me da el siguiente error:
$ touch osada-filesystem
$ truncate -s 2G osada-filesystem 
$ ./osada-format osada-filesystem 
./osada-format - version 3b5a907
stat: Value too large for defined data type

Si me pueden ayudar, estaría buenisimo...

Saludos
Dante Romero

**Comment by mgarciaisaia** [comment]
Efectivamente, es un bug en `osada-format` y `osada-dump`.

Nos faltó [definir `_FILE_OFFSET_BITS`](http://stackoverflow.com/a/13893581/641451) en ambas herramientas, y por eso rompe a los 2GB. En un rato debería estar subiendo el fix, si no me cuelgo mucho.

**Comment by mgarciaisaia** [comment]
Ahí quedó.

Pasando los 2GB empezás a tener _otros_ problemas - en mi VM no puedo mappear 3GB, _creo_ que porque no me alcanza la swap -, pero el tamaño máximo con que vamos a probar el TP es 2GB (por estos motivos, justamente).

El límite de 4GB es de la especificación del filesystem, no de las herramientas.

PD: buenísimo el reporte del bug, che. Gracias :)
